#!/bin/bash - 
#===============================================================================
#
#          FILE: generate_doxygen.sh
# 
#   DESCRIPTION: Generate Doxygen docset 
# 
#       CREATED: 2014-11-09
#
#        AUTHOR: Anthony Dervish
#
#===============================================================================

set -o nounset                              # Treat unset variables as an error

# Get the directory this script lives in, accounting for symlinks to the script
if [ -L "$0" ]; then
  pushd "$(dirname $0)/$(dirname $(readlink "$0"))" >/dev/null
else
  pushd $(dirname "$0") >/dev/null
fi
readonly ScriptDir=$(pwd)
popd >/dev/null

"$ScriptDir"/generate_docs.py -gdoxygen "$@"

# vim: filetype=sh:
